version: '3'

services:
  service_container_db:
    image: postgres:13
    container_name: service_container_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data